### PR TITLE
44 create and implement css styles for profile page

### PR DESCRIPTION
**Pull request by andrewquach-dev**
I finished stylizing the profiles page but also changed a few things and needed everyone's feedback. I noticed I was writing more code and repeating myself when we agreed to use separate CSS files for each page so I researched solutions. I came across express-ejs-layouts which shortened the code and was easier to understand and use than my previous solution. Let me know what you guys think. If you guys want to go back to the old way then I can revert back. 

https://www.figma.com/file/LuREA2TP1nR5stDhxOI6Rp/ProjectHunt?type=design&node-id=133%3A2&mode=design&t=uT9sb5BRP1c2mMnT-1

### CODE REVIEW

**Comment by IreneLinWasHere** [comment]
I think it looks good, but I don't have a good enough understanding of EJS layouts to comment on your code. Looks very succinct, though! What changes did you end up making? I don't see a wireframe for the profiles page on Figma.

**Comment by IreneLinWasHere** [comment]
I think this sounds like a very elegant solution! I'm open to going this route, but I will likely need help getting started.

I think the styles for the profile page looks good, though we might want a little margin between the content and the footer. This would perhaps best be done directly to the footer. 

Also, I noticed that the edit profile button is not functional. Is it safe to assume that we will add this later?

**Comment by andrewquach-dev** [comment]
> I think this sounds like a very elegant solution! I'm open to going this route, but I will likely need help getting started.
> 
> I think the styles for the profile page looks good, though we might want a little margin between the content and the footer. This would perhaps best be done directly to the footer.
> 
> Also, I noticed that the edit profile button is not functional. Is it safe to assume that we will add this later?

We can find a day and time that works for both of us and I can explain it a bit better on voice chat if you'd like!

Good suggestion! I added more margin between the content and the footer because the page looks a bit squished together.

Yes, the edit button is next up on the pipeline. Here is the [task](https://github.com/ImanKahlila/ProjectHunt/issues/42).

**Comment by ThomasCarney315** [comment]
Wow, I really like the sound of this. @andrewquach-dev @ImanKahlila.  What do you all think about having a meeting Friday or Saturday to go over how this works?

**Comment by ImanKahlila** [comment]
> Wow, I really like the sound of this. @andrewquach-dev @ImanKahlila. What do you all think about having a meeting Friday or Saturday to go over how this works?

Sounds good to me! I was just thinking about having a meeting earlier this week, lol. What times on Friday and Saturday are good for you guys? @ThomasCarney315 @andrewquach-dev @IreneLinWasHere

**Review by ThomasCarney315 — APPROVED** [review]

**Review by IreneLinWasHere — APPROVED** [review]
Looks good! Excited to see these changes implemented

**Pull request merged**
