### PR TITLE
39 create and implement css styles for create project page

### PR DESCRIPTION
**Pull request by andrewquach-dev**
I added a temporary header and footer styles from an old web project of mine so that the website wouldn't look so bare. Also, I used clamp variables to make font size, margin, and padding fluid and responsive. Let me know your thoughts

### CODE REVIEW

**Comment by ThomasCarney315** [comment]
@andrewquach-dev, I see you removed the moment-timezone from the package.json. Where is the data coming from?

**Review by ThomasCarney315 — CHANGES_REQUESTED** [review]
Looks great! I just noticed a typo in the footer "#100Devs" is the official spelling

**Comment by andrewquach-dev** [comment]
> @andrewquach-dev, I see you removed the moment-timezone from the package.json. Where is the data coming from?

I removed it because it was deprecated and I couldn't get it to work without making a huge bundle.js file. It's getting the data locally from the browser.

**Comment by ThomasCarney315** [comment]
ah! thats good to know. that's awesome! I was looking for a CDN or something lol

**Review by ThomasCarney315 — APPROVED** [review]

**Review by ImanKahlila — APPROVED** [review]

**Pull request merged**
