### PR TITLE
29 user should be able to create a project specifying name skills skill level GitHub url and meeting times

### PR DESCRIPTION
**Pull request by andrewquach-dev**
These changes are lacking the ability to add technologies used and organization because I think it'd be better to split it up because it might require more collaboration and work.

### CODE REVIEW

**Review by ImanKahlila — CHANGES_REQUESTED** [review]
I have a few questions and suggestions before approving this merge. @andrewquach-dev 

1) Users may want/need to know if a project just started, is in progress, or finished so they can decide on if they can still join or if it's too late to join. What are your thoughts on that?

2) Chelsey @Cheesely @chelseyfoster implemented drop-down categories on Figma file "Browse Projects" under the search bar for "difficulty", "time zone", "bootcamp", and "tech stack" I'm not sure if you were aware of that. So we'll need to code that also.

**Comment by ThomasCarney315** [comment]
@ImanKahlila That's a pretty good idea. We can, of course, include the date of creation/start date and then some options for the 'phase of project' for example: [ Ideation, early, pre-MVP, Maintainance, conversion]. Something we could research.

**Comment by andrewquach-dev** [comment]
> I have a few questions and suggestions before approving this merge. @andrewquach-dev
> 
> 1. Users may want/need to know if a project just started, is in progress, or finished so they can decide on if they can still join or if it's too late to join. What are your thoughts on that?
> 2. Chelsey @Cheesely @chelseyfoster implemented drop-down categories on Figma file "Browse Projects" under the search bar for "difficulty", "time zone", "bootcamp", and "tech stack" I'm not sure if you were aware of that. So we'll need to code that also.

1. I included the option for users to choose the project status upon project creation.
2. Sure we can do that for the browse projects page

**Comment by andrewquach-dev** [comment]
Can you guys test things out and see if there are any errors? Also let me know if you are able to see a created project on your Mongodb

**Comment by ImanKahlila** [comment]
How do I test it out and how do I see if a project was created in my MongoDB? Lol @andrewquach-dev 

I'll approve the merge after I do these things.

**Comment by andrewquach-dev** [comment]
> How do I test it out and how do I see if a project was created in my MongoDB? Lol @andrewquach-dev
> 
> I'll approve the merge after I do these things.

To test it out, follow these steps:
- Follow the instructions in the readme.md file
- Once the website is running, click the login button, fill in credentials, and login
- Click the create project nav item and create a project
- Login to MongoDB and head over to the test collection and check and see if the project exists and contains the proper values.

**Review by ThomasCarney315 — APPROVED** [review]

**Comment by ImanKahlila** [comment]
I've already done the instructions in the readme.md file, so now how do I get the website running? Project Hunt website, right? @andrewquach-dev

**Comment by andrewquach-dev** [comment]
> I've already done the instructions in the readme.md file, so now how do I get the website running? Project Hunt website, right? @andrewquach-dev

Go to http://localhost:{your port number}/ in your browser
Replace {your port number} with the port number you set in the config file

**Comment by ImanKahlila** [comment]
@andrewquach-dev When I click on "Login" it says "Cannot GET /login" 

And I'll know next time to test out everything while we're in the meeting, lol.

**Comment by andrewquach-dev** [comment]
> @andrewquach-dev When I click on "Login" it says "Cannot GET /login"
> 
> And I'll know next time to test out everything while we're in the meeting, lol.

You're using an old version of ProjectHunt and it's probably not in the PR. Check out the PR using this command: 
image

**Comment by ImanKahlila** [comment]
I downloaded GitHub CLI but it says "Authenticate Git with your GitHub credentials? (Y/n)

**Comment by ImanKahlila** [comment]
It says "GraphQL: Could not resolve to a PullRequest with the number of 53. (repository.pullRequest)" @andrewquach-dev

**Comment by andrewquach-dev** [comment]
Try copying the branch name
image

And then checking out the branch with this command:
image

**Comment by ImanKahlila** [comment]
Wait, am I suppose to clone this repo and connect it to Git in order for all of this to work? @andrewquach-dev

**Review by ImanKahlila — APPROVED** [review]

**Pull request merged**
